<html>
<head>
<title>future.py</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<style type="text/css">
.s0 { color: #7a7e85;}
.s1 { color: #bcbec4;}
.s2 { color: #5f826b; font-style: italic;}
.s3 { color: #cf8e6d;}
.s4 { color: #bcbec4;}
</style>
</head>
<body bgcolor="#1e1f22">
<table CELLSPACING=0 CELLPADDING=5 COLS=1 WIDTH="100%" BGCOLOR="#606060" >
<tr><td><center>
<font face="Arial, Helvetica" color="#000000">
future.py</font>
</center></td></tr></table>
<pre><span class="s0"># Copyright 2015 gRPC authors.</span>
<span class="s0">#</span>
<span class="s0"># Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);</span>
<span class="s0"># you may not use this file except in compliance with the License.</span>
<span class="s0"># You may obtain a copy of the License at</span>
<span class="s0">#</span>
<span class="s0">#     http://www.apache.org/licenses/LICENSE-2.0</span>
<span class="s0">#</span>
<span class="s0"># Unless required by applicable law or agreed to in writing, software</span>
<span class="s0"># distributed under the License is distributed on an &quot;AS IS&quot; BASIS,</span>
<span class="s0"># WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.</span>
<span class="s0"># See the License for the specific language governing permissions and</span>
<span class="s0"># limitations under the License.</span>
<span class="s2">&quot;&quot;&quot;A Future interface. 
 
Python doesn't have a Future interface in its standard library. In the absence 
of such a standard, three separate, incompatible implementations 
(concurrent.futures.Future, ndb.Future, and asyncio.Future) have appeared. This 
interface attempts to be as compatible as possible with 
concurrent.futures.Future. From ndb.Future it adopts a traceback-object accessor 
method. 
 
Unlike the concrete and implemented Future classes listed above, the Future 
class defined in this module is an entirely abstract interface that anyone may 
implement and use. 
 
The one known incompatibility between this interface and the interface of 
concurrent.futures.Future is that this interface defines its own CancelledError 
and TimeoutError exceptions rather than raising the implementation-private 
concurrent.futures._base.CancelledError and the 
built-in-but-only-in-3.3-and-later TimeoutError. 
&quot;&quot;&quot;</span>

<span class="s3">import </span><span class="s1">abc</span>


<span class="s3">class </span><span class="s1">TimeoutError</span><span class="s4">(</span><span class="s1">Exception</span><span class="s4">):</span>
    <span class="s2">&quot;&quot;&quot;Indicates that a particular call timed out.&quot;&quot;&quot;</span>


<span class="s3">class </span><span class="s1">CancelledError</span><span class="s4">(</span><span class="s1">Exception</span><span class="s4">):</span>
    <span class="s2">&quot;&quot;&quot;Indicates that the computation underlying a Future was cancelled.&quot;&quot;&quot;</span>


<span class="s3">class </span><span class="s1">Future</span><span class="s4">(</span><span class="s1">abc</span><span class="s4">.</span><span class="s1">ABC</span><span class="s4">):</span>
    <span class="s2">&quot;&quot;&quot;A representation of a computation in another control flow. 
 
    Computations represented by a Future may be yet to be begun, may be ongoing, 
    or may have already completed. 
    &quot;&quot;&quot;</span>

    <span class="s0"># NOTE(nathaniel): This isn't the return type that I would want to have if it</span>
    <span class="s0"># were up to me. Were this interface being written from scratch, the return</span>
    <span class="s0"># type of this method would probably be a sum type like:</span>
    <span class="s0">#</span>
    <span class="s0"># NOT_COMMENCED</span>
    <span class="s0"># COMMENCED_AND_NOT_COMPLETED</span>
    <span class="s0"># PARTIAL_RESULT&lt;Partial_Result_Type&gt;</span>
    <span class="s0"># COMPLETED&lt;Result_Type&gt;</span>
    <span class="s0"># UNCANCELLABLE</span>
    <span class="s0"># NOT_IMMEDIATELY_DETERMINABLE</span>
    <span class="s4">@</span><span class="s1">abc</span><span class="s4">.</span><span class="s1">abstractmethod</span>
    <span class="s3">def </span><span class="s1">cancel</span><span class="s4">(</span><span class="s1">self</span><span class="s4">):</span>
        <span class="s2">&quot;&quot;&quot;Attempts to cancel the computation. 
 
        This method does not block. 
 
        Returns: 
          True if the computation has not yet begun, will not be allowed to take 
            place, and determination of both was possible without blocking. False 
            under all other circumstances including but not limited to the 
            computation's already having begun, the computation's already having 
            finished, and the computation's having been scheduled for execution on a 
            remote system for which a determination of whether or not it commenced 
            before being cancelled cannot be made without blocking. 
        &quot;&quot;&quot;</span>
        <span class="s3">raise </span><span class="s1">NotImplementedError</span><span class="s4">()</span>

    <span class="s0"># NOTE(nathaniel): Here too this isn't the return type that I'd want this</span>
    <span class="s0"># method to have if it were up to me. I think I'd go with another sum type</span>
    <span class="s0"># like:</span>
    <span class="s0">#</span>
    <span class="s0"># NOT_CANCELLED (this object's cancel method hasn't been called)</span>
    <span class="s0"># NOT_COMMENCED</span>
    <span class="s0"># COMMENCED_AND_NOT_COMPLETED</span>
    <span class="s0"># PARTIAL_RESULT&lt;Partial_Result_Type&gt;</span>
    <span class="s0"># COMPLETED&lt;Result_Type&gt;</span>
    <span class="s0"># UNCANCELLABLE</span>
    <span class="s0"># NOT_IMMEDIATELY_DETERMINABLE</span>
    <span class="s0">#</span>
    <span class="s0"># Notice how giving the cancel method the right semantics obviates most</span>
    <span class="s0"># reasons for this method to exist.</span>
    <span class="s4">@</span><span class="s1">abc</span><span class="s4">.</span><span class="s1">abstractmethod</span>
    <span class="s3">def </span><span class="s1">cancelled</span><span class="s4">(</span><span class="s1">self</span><span class="s4">):</span>
        <span class="s2">&quot;&quot;&quot;Describes whether the computation was cancelled. 
 
        This method does not block. 
 
        Returns: 
          True if the computation was cancelled any time before its result became 
            immediately available. False under all other circumstances including but 
            not limited to this object's cancel method not having been called and 
            the computation's result having become immediately available. 
        &quot;&quot;&quot;</span>
        <span class="s3">raise </span><span class="s1">NotImplementedError</span><span class="s4">()</span>

    <span class="s4">@</span><span class="s1">abc</span><span class="s4">.</span><span class="s1">abstractmethod</span>
    <span class="s3">def </span><span class="s1">running</span><span class="s4">(</span><span class="s1">self</span><span class="s4">):</span>
        <span class="s2">&quot;&quot;&quot;Describes whether the computation is taking place. 
 
        This method does not block. 
 
        Returns: 
          True if the computation is scheduled to take place in the future or is 
            taking place now, or False if the computation took place in the past or 
            was cancelled. 
        &quot;&quot;&quot;</span>
        <span class="s3">raise </span><span class="s1">NotImplementedError</span><span class="s4">()</span>

    <span class="s0"># NOTE(nathaniel): These aren't quite the semantics I'd like here either. I</span>
    <span class="s0"># would rather this only returned True in cases in which the underlying</span>
    <span class="s0"># computation completed successfully. A computation's having been cancelled</span>
    <span class="s0"># conflicts with considering that computation &quot;done&quot;.</span>
    <span class="s4">@</span><span class="s1">abc</span><span class="s4">.</span><span class="s1">abstractmethod</span>
    <span class="s3">def </span><span class="s1">done</span><span class="s4">(</span><span class="s1">self</span><span class="s4">):</span>
        <span class="s2">&quot;&quot;&quot;Describes whether the computation has taken place. 
 
        This method does not block. 
 
        Returns: 
          True if the computation is known to have either completed or have been 
            unscheduled or interrupted. False if the computation may possibly be 
            executing or scheduled to execute later. 
        &quot;&quot;&quot;</span>
        <span class="s3">raise </span><span class="s1">NotImplementedError</span><span class="s4">()</span>

    <span class="s4">@</span><span class="s1">abc</span><span class="s4">.</span><span class="s1">abstractmethod</span>
    <span class="s3">def </span><span class="s1">result</span><span class="s4">(</span><span class="s1">self</span><span class="s4">, </span><span class="s1">timeout</span><span class="s4">=</span><span class="s3">None</span><span class="s4">):</span>
        <span class="s2">&quot;&quot;&quot;Accesses the outcome of the computation or raises its exception. 
 
        This method may return immediately or may block. 
 
        Args: 
          timeout: The length of time in seconds to wait for the computation to 
            finish or be cancelled, or None if this method should block until the 
            computation has finished or is cancelled no matter how long that takes. 
 
        Returns: 
          The return value of the computation. 
 
        Raises: 
          TimeoutError: If a timeout value is passed and the computation does not 
            terminate within the allotted time. 
          CancelledError: If the computation was cancelled. 
          Exception: If the computation raised an exception, this call will raise 
            the same exception. 
        &quot;&quot;&quot;</span>
        <span class="s3">raise </span><span class="s1">NotImplementedError</span><span class="s4">()</span>

    <span class="s4">@</span><span class="s1">abc</span><span class="s4">.</span><span class="s1">abstractmethod</span>
    <span class="s3">def </span><span class="s1">exception</span><span class="s4">(</span><span class="s1">self</span><span class="s4">, </span><span class="s1">timeout</span><span class="s4">=</span><span class="s3">None</span><span class="s4">):</span>
        <span class="s2">&quot;&quot;&quot;Return the exception raised by the computation. 
 
        This method may return immediately or may block. 
 
        Args: 
          timeout: The length of time in seconds to wait for the computation to 
            terminate or be cancelled, or None if this method should block until 
            the computation is terminated or is cancelled no matter how long that 
            takes. 
 
        Returns: 
          The exception raised by the computation, or None if the computation did 
            not raise an exception. 
 
        Raises: 
          TimeoutError: If a timeout value is passed and the computation does not 
            terminate within the allotted time. 
          CancelledError: If the computation was cancelled. 
        &quot;&quot;&quot;</span>
        <span class="s3">raise </span><span class="s1">NotImplementedError</span><span class="s4">()</span>

    <span class="s4">@</span><span class="s1">abc</span><span class="s4">.</span><span class="s1">abstractmethod</span>
    <span class="s3">def </span><span class="s1">traceback</span><span class="s4">(</span><span class="s1">self</span><span class="s4">, </span><span class="s1">timeout</span><span class="s4">=</span><span class="s3">None</span><span class="s4">):</span>
        <span class="s2">&quot;&quot;&quot;Access the traceback of the exception raised by the computation. 
 
        This method may return immediately or may block. 
 
        Args: 
          timeout: The length of time in seconds to wait for the computation to 
            terminate or be cancelled, or None if this method should block until 
            the computation is terminated or is cancelled no matter how long that 
            takes. 
 
        Returns: 
          The traceback of the exception raised by the computation, or None if the 
            computation did not raise an exception. 
 
        Raises: 
          TimeoutError: If a timeout value is passed and the computation does not 
            terminate within the allotted time. 
          CancelledError: If the computation was cancelled. 
        &quot;&quot;&quot;</span>
        <span class="s3">raise </span><span class="s1">NotImplementedError</span><span class="s4">()</span>

    <span class="s4">@</span><span class="s1">abc</span><span class="s4">.</span><span class="s1">abstractmethod</span>
    <span class="s3">def </span><span class="s1">add_done_callback</span><span class="s4">(</span><span class="s1">self</span><span class="s4">, </span><span class="s1">fn</span><span class="s4">):</span>
        <span class="s2">&quot;&quot;&quot;Adds a function to be called at completion of the computation. 
 
        The callback will be passed this Future object describing the outcome of 
        the computation. 
 
        If the computation has already completed, the callback will be called 
        immediately. 
 
        Args: 
          fn: A callable taking this Future object as its single parameter. 
        &quot;&quot;&quot;</span>
        <span class="s3">raise </span><span class="s1">NotImplementedError</span><span class="s4">()</span>
</pre>
</body>
</html>